version: '3.4'

services:
  db:
    image: mariadb
    volumes:
    - db_data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mhteaser
    ports:
    - "3306:3306"

  wordpress:
    depends_on:
    - db
    image: wordpress:latest
    ports:
    - "8888:80"
    volumes:
    - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: mhteaser
volumes:
  db_data:
    name: mhteaser